// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'config/app_env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// API keys and project IDs are loaded from the gitignored `.env` file.
/// Copy `.env.example` to `.env` before running.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: AppEnv.firebaseApiKey,
        appId: AppEnv.firebaseWebAppId,
        messagingSenderId: AppEnv.firebaseMessagingSenderId,
        projectId: AppEnv.firebaseProjectId,
        authDomain: AppEnv.firebaseAuthDomain,
        databaseURL: AppEnv.firebaseDatabaseUrl,
        storageBucket: AppEnv.firebaseStorageBucket,
        measurementId: AppEnv.firebaseMeasurementId,
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: AppEnv.firebaseApiKey,
        appId: AppEnv.firebaseAndroidAppId,
        messagingSenderId: AppEnv.firebaseMessagingSenderId,
        projectId: AppEnv.firebaseProjectId,
        authDomain: AppEnv.firebaseAuthDomain,
        databaseURL: AppEnv.firebaseDatabaseUrl,
        storageBucket: AppEnv.firebaseStorageBucket,
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: AppEnv.firebaseApiKey,
        appId: AppEnv.firebaseIosAppId,
        messagingSenderId: AppEnv.firebaseMessagingSenderId,
        projectId: AppEnv.firebaseProjectId,
        authDomain: AppEnv.firebaseAuthDomain,
        databaseURL: AppEnv.firebaseDatabaseUrl,
        storageBucket: AppEnv.firebaseStorageBucket,
        iosClientId: AppEnv.firebaseIosClientId,
        iosBundleId: 'com.ghartek.app',
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: AppEnv.firebaseApiKey,
        appId: AppEnv.firebaseIosAppId,
        messagingSenderId: AppEnv.firebaseMessagingSenderId,
        projectId: AppEnv.firebaseProjectId,
        authDomain: AppEnv.firebaseAuthDomain,
        databaseURL: AppEnv.firebaseDatabaseUrl,
        storageBucket: AppEnv.firebaseStorageBucket,
        iosClientId: AppEnv.firebaseIosClientId,
        iosBundleId: 'com.ghartek.app',
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: AppEnv.firebaseApiKey,
        appId: AppEnv.firebaseWebAppId,
        messagingSenderId: AppEnv.firebaseMessagingSenderId,
        projectId: AppEnv.firebaseProjectId,
        authDomain: AppEnv.firebaseAuthDomain,
        databaseURL: AppEnv.firebaseDatabaseUrl,
        storageBucket: AppEnv.firebaseStorageBucket,
      );
}
